---
- name: Restart Ollama
  ansible.builtin.systemd_service:
    name: ollama
    daemon_reload: true
    state: restarted

- name: Restart Ollama GPU telemetry
  when: not ansible_check_mode
  ansible.builtin.systemd_service:
    name: ollama-gpu-telemetry
    daemon_reload: true
    state: restarted
