---
- name: Update operating-system CA trust
  ansible.builtin.command: /usr/sbin/update-ca-certificates
  changed_when: true
  listen: update operating-system CA trust

- name: Restart nftables
  ansible.builtin.systemd_service:
    name: nftables
    state: restarted
  listen: restart nftables

- name: Restart Loki
  ansible.builtin.systemd_service:
    name: loki
    state: restarted
  listen: restart Loki

- name: Restart Tempo
  ansible.builtin.systemd_service:
    name: tempo
    state: restarted
  listen: restart Tempo

- name: Restart Prometheus
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
  listen: restart Prometheus

- name: Restart Grafana
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted
    daemon_reload: true
  listen: restart Grafana

- name: Restart Alloy
  ansible.builtin.systemd_service:
    name: alloy
    state: restarted
  listen: restart Alloy

- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
  listen: restart journald
