apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage-pv.yaml
  - storage-pvc.yaml
  - postgres.yaml
  - ledger-web-service.yaml
  - oauth2-proxy.yaml
  - ledger-ingress.yaml

images:
  - name: ghcr.io/larocquemb/home-budget-pipeline
    newTag: 6ff1f6d18b8f80b2313934b998a73faa25cd3100
