apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage-pv.yaml
  - storage-pvc.yaml
  - postgres.yaml
  - postgres-ingressroutetcp.yaml
  - receipt-processing-reset-job.yaml
  - ledger-web-service.yaml
  - oauth2-proxy.yaml
  - ledger-ingress.yaml
  - receipt-processor-cronjob.yaml

images:
  - name: ghcr.io/larocquemb/home-budget-pipeline
    newTag: 8cef570e7eda23bdd59b2c86b3c8d80b4e4f6a24
