apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage-pv.yaml
  - storage-pvc.yaml
  - postgres.yaml
  - ledger-web-service.yaml
  - oauth2-proxy.yaml
  - ledger-ingress.yaml

images:
  - name: ghcr.io/larocquemb/home-budget-pipeline
    newTag: 62340a18851afd95edd120b12c90fbc1d4595185
