apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ledger
  namespace: home-budget
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - idc.brownrook.com
      secretName: idc-brownrook-com-tls
  rules:
    - host: idc.brownrook.com
      http:
        paths:
          - path: /ledger
            pathType: Prefix
            backend:
              service:
                name: ledger-oauth2-proxy
                port:
                  number: 4180
