apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-budget-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0775
    - file_mode=0664
    - uid=1000
    - gid=1000
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: home-budget-data
    volumeAttributes:
      source: //pve/files
      subDir: brownrook/home-budget
    nodeStageSecretRef:
      name: pve-smb-credentials
      namespace: home-budget
