apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../rabbitmq-private-telemetry
  - neo4j.yaml
  - projector.yaml
  - web-rbac.yaml
  - network-policy.yaml
patches:
  - path: web-patch.yaml
replacements:
  - source:
      kind: Deployment
      name: ledger-web
      fieldPath: spec.template.spec.containers.[name=ledger-web].image
    targets:
      - select:
          kind: CronJob
          name: receipt-graph
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.[name=graph].image
