apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../rabbitmq-private-logging
  - ../opentelemetry
  - ../public-telemetry
patches:
  - path: receipt-worker-telemetry-patch.yaml
