BEGIN;

CREATE TABLE IF NOT EXISTS budget.merchant_aliases (
    id BIGSERIAL PRIMARY KEY,
    alias_name TEXT NOT NULL UNIQUE,
    merchant_name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
